services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend_network
    restart: unless-stopped

  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - backend_network
    restart: unless-stopped

  celery:
    build: .
    command: celery -A painaway worker --loglevel=info
    env_file:
      - .env
    depends_on:
      - web
      - redis
    networks:
      - backend_network
    restart: unless-stopped

  celery-beat:
    build: .
    command: celery -A painaway beat --loglevel=info
    env_file:
      - .env
    depends_on:
      - web
      - redis
    networks:
      - backend_network
    restart: unless-stopped

volumes:
  redis_data:

networks:
  backend_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.28.0.0/24